### PR TITLE
Close fd on /dev/null on exec to silence SELinux AVCs

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Review by eric-ch — APPROVED** [review]
LGTM.

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1611

**Comment by eric-ch** [comment]
~~Will merge soon.~~
See stable-8 PR.

**Comment by eric-ch** [comment]
I no longer see the {{avc:}} on recent master builds without this change...

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/1702

**Pull request closed without merging**
